import Head from 'next/head';
import Header from '../components/header/header';
import UpperLinks from '../components/UpperLinks/upperLinks';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Meetshm | Digital Marketing Agency</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<UpperLinks />
			<Header />
		</div>
	);
}
